name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from VERSION file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/sight-ai/sight-datadao-satya-proof:${{ env.VERSION }}
            ghcr.io/sight-ai/sight-datadao-satya-proof:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export Docker Image to File
        run: |
          docker pull ghcr.io/sight-ai/sight-datadao-satya-proof:${{ env.VERSION }}
          docker save ghcr.io/sight-ai/sight-datadao-satya-proof:${{ env.VERSION }} | gzip > sight-datadao-satya-proof-${{ env.VERSION }}.tar.gz

      - name: Generate release body
        run: |
          echo "Image SHA256: $(sha256sum sight-datadao-satya-proof-${{ env.VERSION }}.tar.gz | cut -d' ' -f1)" >> release_body.txt

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sight-datadao-satya-proof-image
          path: sight-datadao-satya-proof-${{ env.VERSION }}.tar.gz

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: release_body.txt
          draft: false
          prerelease: false
          files: |
            ./sight-datadao-satya-proof-${{ env.VERSION }}.tar.gz

      - name: Log build result
        if: always()
        run: |
          if [ ${{ job.status }} == "success" ]; then
            echo "Build and release completed successfully"
          else
            echo "Build and release failed"
          fi
